WebExperience.Test/Models/Asset.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;

namespace WebExperience.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [JsonProperty(PropertyName = "assetId")]
        public Guid AssetId { get; set; }
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }
        [JsonProperty(PropertyName = "mimeType")]
        public string MimeType { get; set; }
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
    }
}

WebExperience.Test/ViewModels/AssetViewModel.cs
using System;

using Newtonsoft.Json;

namespace WebExperience.Test.ViewModels
{
    public class AssetViewModel
    {
        [JsonProperty(PropertyName = "assetId")]
        public Guid AssetId { get; set; }
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }
        [JsonProperty(PropertyName = "mimeType")]
        public string MimeType { get; set; }
        [JsonProperty(PropertyName = "createdBy")]
        public string CreatedBy { get; set; }
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }
    }
}

WebExperience.Test/Controllers/Api/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;

using WebExperience.Test.Models;
using WebExperience.Test.ViewModels;

namespace WebExperience.Test.Controllers.Api
{
    public class AssetsController : ApiController
    {
        private AssetContext db = new AssetContext();

        // GET: api/Assets
        public ResultList<AssetViewModel> Get([FromUri] QueryOptions queryOptions)
        {
            var start = (queryOptions.CurrentPage - 1) * queryOptions.PageSize;

            var assets = db.Assets
                .OrderBy(queryOptions.Sort)
                .Skip(start)
                .Take(queryOptions.PageSize);

            queryOptions.TotalPages = (int)Math.Ceiling((double)db.Assets.Count() / queryOptions.PageSize);

            AutoMapper.Mapper.CreateMap<Asset, AssetViewModel>();

            return new ResultList<AssetViewModel> {
                QueryOptions = queryOptions,
                Results = AutoMapper.Mapper.Map<List<Asset>, List<AssetViewModel>>(assets.ToList())
            };
        }

        // PUT(edit): api/Assets/5
        [ResponseType(typeof(void))]
        public IHttpActionResult Put(AssetViewModel asset)
        {
            if(!ModelState.IsValid) {
                return BadRequest(ModelState);
            }
            AutoMapper.Mapper.CreateMap<AssetViewModel, Asset>();
            db.Entry(AutoMapper.Mapper.Map<AssetViewModel, Asset>(asset)).State = EntityState.Modified;
            db.SaveChanges();
            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST(create): api/Assets
        [ResponseType(typeof(AssetViewModel))]
        public IHttpActionResult Post(AssetViewModel asset)
        {
            if(!ModelState.IsValid) {
                return BadRequest(ModelState);
            }
            asset.AssetId = Guid.NewGuid();
            AutoMapper.Mapper.CreateMap<AssetViewModel, Asset>();
            db.Assets.Add(AutoMapper.Mapper.Map<AssetViewModel, Asset>(asset));
            db.SaveChanges();
            return CreatedAtRoute("DefaultApi", new { id = asset.AssetId }, asset);
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebExperience.Test/Controllers/AssetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web.ModelBinding;
using System.Web.Mvc;

using WebExperience.Test.Models;
using WebExperience.Test.ViewModels;

namespace WebExperience.Test.Controllers
{
    public class AssetsController : Controller
    {
        private AssetContext db = new AssetContext();

        // GET: Assets
        public ActionResult Index([Form] QueryOptions queryOptions)
        {
            var start = (queryOptions.CurrentPage - 1) * queryOptions.PageSize;

            var assets = db.Assets
                .OrderBy(queryOptions.Sort)
                .Skip(start)
                .Take(queryOptions.PageSize);

            queryOptions.TotalPages = (int)Math.Ceiling((double)db.Assets.Count() / queryOptions.PageSize);

            AutoMapper.Mapper.CreateMap<Asset, AssetViewModel>();

            return View(new ResultList<AssetViewModel> {
                QueryOptions = queryOptions,
                Results = AutoMapper.Mapper.Map<List<Asset>, List<AssetViewModel>>(assets.ToList())
            });
        }

        // GET: Assets/Details/5
        public ActionResult Details(Guid? id)
        {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Assets.Find(id);
            if(asset == null) {
                return HttpNotFound();
            }
            return View(asset);
        }

        // GET: Assets/Create
        public ActionResult Create()
        {
            return View(new AssetViewModel());
        }

        // GET: Assets/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Assets.Find(id);
            if(asset == null) {
                return HttpNotFound();
            }

            AutoMapper.Mapper.CreateMap<Asset, AssetViewModel>();
            return View(AutoMapper.Mapper.Map<Asset, AssetViewModel>(asset));
        }

        // GET: Assets/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = db.Assets.Find(id);
            if(asset == null) {
                return HttpNotFound();
            }

            AutoMapper.Mapper.CreateMap<Asset, AssetViewModel>();
            return View(AutoMapper.Mapper.Map<Asset, AssetViewModel>(asset));
        }

        // POST: Assets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Asset asset = db.Assets.Find(id);
            db.Assets.Remove(asset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebExperience.Test/Views/Assets/Create.cshtml
@model WebExperience.Test.ViewModels.AssetViewModel

@{ ViewBag.Title = "Create"; }

<div data-bind="visible: !saveCompleted()">

    <h2>Create</h2>

    @using(Html.BeginForm("Create", "Assets", FormMethod.Post, new {
        data_bind = "submit: save"
    })) {

@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Asset</h4>
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(model => model.FileName, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FileName, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.fileName"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MimeType, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MimeType, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.mimeType"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CreatedBy, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.createdBy"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.email"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Country, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Country, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.country"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.description"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10" data-bind="visible: !sending()">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </div>
                </div>}
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "/ViewModels/AssetCreateViewModel.js")
    <script>
        var viewModel = new AssetCreateViewModel();
        ko.applyBindings(viewModel);
    </script>
}

WebExperience.Test/Views/Assets/Delete.cshtml
@model WebExperience.Test.ViewModels.AssetViewModel

@{ ViewBag.Title = "Delete";
    Layout = null; }

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Asset Delete Confirmation</h4>
            </div>
            <div class="modal-body">
                <h3>Are you sure you want to delete this asset ?</h3>
                <div>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.FileName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FileName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.MimeType)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.MimeType)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.CreatedBy)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Country)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Country)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                    </dl>
                </div>
            </div>

            <div class="modal-footer">
                @using(Html.BeginForm("Delete", "Assets", FormMethod.Post,
                new { data_bind = "submit: delete" })) {
    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center"
                         data-bind="visible: !sending()">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">
                            Close
                        </button>
                    </div>}
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

WebExperience.Test/Views/Assets/Details.cshtml
@model WebExperience.Test.Models.Asset

@{ ViewBag.Title = "Details"; }

<h2>Details</h2>

<div>
    <h4>Asset</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AssetId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebExperience.Test/Views/Assets/Edit.cshtml
@using WebExperience.Test.Extensions
@model WebExperience.Test.ViewModels.AssetViewModel

@{ ViewBag.Title = "Edit"; }

<div data-bind="visible: !saveCompleted()">

    <h2>Edit</h2>

    @using(Html.BeginForm("Edit", "Assets", FormMethod.Post, new { data_bind = "submit: edit" })) {

@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Asset</h4>
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.FileName, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.fileName"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MimeType, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.mimeType"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CreatedBy, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.createdBy"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.email"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Country, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Country, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.country"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new {
                            @class = "control-label col-md-2"
                        })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new {
                                htmlAttributes = new {
                                    @class = "form-control",
                                    data_bind = "value: asset.description"
                                }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10" data-bind="visible: !sending()">
                            <input type="submit" value="@Html.Raw("Edit")" class="btn btn-primary" />
                        </div>
                    </div>
                </div>}
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "/ViewModels/AssetEditViewModel.js")
    <script>
        var viewModel = new AssetEditViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}

WebExperience.Test/Views/Assets/Index.cshtml
@using WebExperience.Test.Extensions
@using WebExperience.Test.ViewModels
@model ResultList<AssetViewModel>

@{ ViewBag.Title = "Assets";
    var queryOptions = Model.QueryOptions; }

<h2>Assets</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Controller", new { @class = "btn btn-success" })
</p>

<div style="display: none" data-bind="visible:  pagingService.entities().length > 0">
    <table class="table">
        <thead>
            <tr>
                <th>File name</th>
                <th>Created by</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: pagingService.entities">
            <tr>
                <td data-bind="text: fileName"></td>
                <td data-bind="text: createdBy"></td>
                <td>
                    <a data-bind="attr: { href: '@Url.Action("Details")/' + assetId }" class="btn btn-info">Details</a>
                    <a data-bind="attr: { href: '@Url.Action("Edit")/' + assetId }" class="btn btn-primary">Edit</a>
                    <a data-bind="click: $parent.showDeleteModal, attr: { href: '@Url.Action("Delete")/' + assetId }" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        </tbody>

    </table>

    @Html.BuildNextPreviousLinks("Index")
</div>

<div style="display: none" data-bind="visible: pagingService.entities().length == 0" class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
    </button>
    There are no assets to display. Click @Html.ActionLink("here", "Create") to create one now.
</div>

@section Scripts {
    @Scripts.Render("/Scripts/Services/PagingService.js", "/ViewModels/AssetIndexViewModel.js")
    <script>
        var viewModel = new AssetIndexViewModel(@Html.HtmlConvertToJson(Model));
        ko.applyBindings(viewModel);
    </script>
}